spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: 123456
    virtual-host: /

  application:
    name: service-gateway
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:
        locator:
          enabled: true #gateway开启服务注册和发现的功能 自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true #服务名配置为小写
      routes:
        - id: baidu                     #网关路由到网易官网
          uri: http://www.baidu.com/
          predicates:
            - Path=/baidu/**
        - id: demo-server
          uri: lb://DEMO-SERVER
          predicates:
            - Path=/demo/**

server:l
  port: 2004


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
