spring:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: 123456
    virtual-host: /

  application:
    name: service-gateway
  cloud:        # spring cloud gateway 路由配置方式
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: 163                     #网关路由到网易官网
          uri: http://www.163.com/
          predicates:
            - Path=/163/**
        - id: rabbitmq-server           #网关路由到订单服务rabbitmq-server
          uri: lb://rabbitmq-server
          predicates:
            - Path=/rabbitmq-server/**
        - id: demo-server
          uri: lb://demo-server
          predicates:
            - Path=/demo-server/**

server:
  port: 2004


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
